@user=yangwawa0323
@password=redhat

### @name getAllVideos
GET http://localhost:8080/videos
Content-Type: application/json
Authorization: Basic {{user}}:{{password}}

### @name missingAuthor
POST http://localhost:8080/videos
Content-Type: application/json
Authorization: Basic {{user}}:{{password}}

{
  "title": "Title 1",
  "description": "The description 1",
  "url": "http://localhost:8000/videos/1"
}

### @name titleIsTooShort
POST http://localhost:8080/videos
Content-Type: application/json
Authorization: Basic {{user}}:{{password}}

{
  "title": "T",
  "description": "The description 1",
  "url": "http://localhost:8000/videos/1",
  "author": "yangwawa0323"
}

### @name badEmailFormat
POST http://localhost:8080/videos
Content-Type: application/json
Authorization: Basic {{user}}:{{password}}

{
  "title": "The title",
  "description": "The description 1",
  "url": "http://localhost:8000/videos/1",
  "author": {
    "first_name" : "yang",
    "last_name" : "ken",
    "age": 46,
    "email": "163.com"
  }
}

### @name titleIsTooLong
POST http://localhost:8080/videos
Content-Type: application/json
Authorization: Basic {{user}}:{{password}}

{
  "title": "The loooooong title 1",
  "description": "The description 1",
  "url": "http://localhost:8000/videos/1",
  "author": {
    "first_name" : "yang",
    "last_name" : "ken",
    "age": 46,
    "email": "163.com"
  }
}

### @name saveVideo
POST http://localhost:8080/videos
Content-Type: application/json
Authorization: Basic {{user}}:{{password}}

{
  "title": "Title 1",
  "description": "The description 1",
  "url": "http://localhost:8000/videos/1",
  "author": {
    "first_name" : "yang",
    "last_name" : "ken",
    "age": 46,
    "email": "yangwawa0323@163.com"
  }
}


### @name saveVideoAgain
POST http://localhost:8080/videos
Content-Type: application/json
Authorization: Basic {{user}}:{{password}}

{
  "title": "The title",
  "description": "The description 2",
  "url": "http://localhost:8000/videos/2",
  "author": {
    "first_name" : "yang",
    "last_name" : "ken",
    "age": 46,
    "email": "12238747@qq.com"
  }
}